CREATE TABLE "CATEGORY"
(
    "CATEGORY_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "CHARACTERISTIC" CHAR(50) NOT NULL ENABLE,
    CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID") ENABLE
);

CREATE TABLE "ORGANIZATION_LEGAL_FORM"
(
    "ORGANIZATION_LEGAL_FORM_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CONSTRAINT "ORGANIZATION_LEGAL_FORM_PK" PRIMARY KEY ("ORGANIZATION_LEGAL_FORM_ID") ENABLE
);

CREATE TABLE "STREET"
(
    "STREET_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CONSTRAINT "STREET_PK" PRIMARY KEY ("STREET_ID") ENABLE
);

CREATE TABLE "TYPE_OF_OWNERSHIP"
(
    "TYPE_OF_OWNERSHIP_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    CONSTRAINT "TYPE_OF_OWNERSHIP_PK" PRIMARY KEY ("TYPE_OF_OWNERSHIP_ID") ENABLE
);
CREATE TABLE "ORGANIZATION"
(
    "ORGANIZATION_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "STREET_ID" NUMBER NOT NULL ENABLE,
    "INN" NUMBER NOT NULL ENABLE,
    "PHONE_NUM" CHAR(15) NOT NULL ENABLE,
    "HOUSE_NUM" CHAR(10) NOT NULL ENABLE,
    "OFFICE_NUM" CHAR(10) NOT NULL ENABLE,
    "DIRECTOR_SURNAME" CHAR(20) NOT NULL ENABLE,
    "TYPE_OF_OWNERSHIP_ID" NUMBER NOT NULL ENABLE,
    "ORGANIZATION_LEGAL_FORM_ID" NUMBER NOT NULL ENABLE,
    CONSTRAINT "ORGANIZATION_PK" PRIMARY KEY ("ORGANIZATION_ID") ENABLE,
    CONSTRAINT "ORGANIZATION_FK" FOREIGN KEY ("STREET_ID")
        REFERENCES "STREET" ("STREET_ID") ON DELETE CASCADE ENABLE,
    CONSTRAINT "ORGANIZATION_FK2" FOREIGN KEY ("TYPE_OF_OWNERSHIP_ID")
        REFERENCES "TYPE_OF_OWNERSHIP" ("TYPE_OF_OWNERSHIP_ID") ON DELETE CASCADE ENABLE,
    CONSTRAINT "ORGANIZATION_FK3" FOREIGN KEY ("ORGANIZATION_LEGAL_FORM_ID")
        REFERENCES "ORGANIZATION_LEGAL_FORM" ("ORGANIZATION_LEGAL_FORM_ID") ON DELETE CASCADE ENABLE
);

CREATE TABLE "DELIVERY"
(
    "DELIVERY_ID" NUMBER NOT NULL ENABLE,
    "DATE_DELIVERY" DATE NOT NULL ENABLE,
    "MANUFACTURER_ID" NUMBER NOT NULL ENABLE,
    "CONSUMER_ID" NUMBER NOT NULL ENABLE,
    CONSTRAINT "DELIVERY_PK" PRIMARY KEY ("DELIVERY_ID") ENABLE,
    CONSTRAINT "DELIVERY_FK" FOREIGN KEY ("MANUFACTURER_ID")
        REFERENCES "ORGANIZATION" ("ORGANIZATION_ID") ON DELETE CASCADE ENABLE,
    CONSTRAINT "DELIVERY_FK2" FOREIGN KEY ("CONSUMER_ID")
        REFERENCES "ORGANIZATION" ("ORGANIZATION_ID") ON DELETE CASCADE ENABLE
);

CREATE TABLE "PRODUCTS"
(
    "PRODUCTS_ID" NUMBER NOT NULL ENABLE,
    "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PRICE" BINARY_DOUBLE NOT NULL ENABLE,
    "EXPIRATION_DATE" DATE NOT NULL ENABLE,
    "CATEGORY_ID" NUMBER NOT NULL ENABLE,
    CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCTS_ID") ENABLE,
    CONSTRAINT "PRODUCTS_FK" FOREIGN KEY ("CATEGORY_ID")
        REFERENCES "CATEGORY" ("CATEGORY_ID") ON DELETE CASCADE ENABLE
);

CREATE TABLE "CUSTOM_PRODUCTS"
(
    "CUSTOM_PRODUCTS_ID" NUMBER NOT NULL ENABLE,
    "DELIVERY_ID" NUMBER NOT NULL ENABLE,
    "PRODUCTS_ID" NUMBER NOT NULL ENABLE,
    "PRODUCTS_COUNT" NUMBER NOT NULL ENABLE,
    CONSTRAINT "CUSTOM_PRODUCTS_PK" PRIMARY KEY ("CUSTOM_PRODUCTS_ID") ENABLE,
    CONSTRAINT "CUSTOM_PRODUCTS_FK" FOREIGN KEY ("DELIVERY_ID")
        REFERENCES "DELIVERY" ("DELIVERY_ID") ON DELETE CASCADE ENABLE,
    CONSTRAINT "CUSTOM_PRODUCTS_FK2" FOREIGN KEY ("PRODUCTS_ID")
        REFERENCES "PRODUCTS" ("PRODUCTS_ID") ON DELETE CASCADE ENABLE
);